#!/usr/bin/env bash
# Run the instantiation validator against an engine output directory
# and produce a `revise-report.md` with a machine-parseable YAML
# frontmatter. Used by drill-down-engine / audit-and-remediate as
# the mandatory revise step.
#
# Usage:
#   bash scripts/revise.sh [prompts/outputs/current]
#
# Exit codes:
#   0  validator passed, revise-report.md written with executor_gate: pass
#   1  validator failed, revise-report.md written with executor_gate: fail
#      (re-run the engine for the offending files, then re-invoke revise.sh)
#   2  preconditions missing (no plan files at all, no scripts dir, etc.)

set -uo pipefail

TARGET_DIR="${1:-prompts/outputs/current}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VALIDATOR="$SCRIPT_DIR/validate-instantiation.sh"

if [ ! -d "$TARGET_DIR" ]; then
  echo "❌ $TARGET_DIR does not exist" >&2
  exit 2
fi

if [ ! -x "$VALIDATOR" ]; then
  echo "❌ validator not found or not executable: $VALIDATOR" >&2
  exit 2
fi

# Infer engine from what's present. The revise-report frontmatter names it.
shopt -s nullglob
remediation_files=("$TARGET_DIR"/remediation-*.md)
tasks_files=("$TARGET_DIR"/tasks-*.md)

if [ ${#remediation_files[@]} -gt 0 ]; then
  engine="audit-and-remediate"
  plan_count=${#remediation_files[@]}
elif [ ${#tasks_files[@]} -gt 0 ]; then
  engine="drill-down-engine"
  plan_count=${#tasks_files[@]}
else
  echo "❌ no remediation-*.md or tasks-*.md in $TARGET_DIR — run an engine first" >&2
  exit 2
fi

REPORT="$TARGET_DIR/revise-report.md"
NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# Run validator, capture both exit code and output.
VAL_OUT_FILE=$(mktemp)
"$VALIDATOR" "$TARGET_DIR" > "$VAL_OUT_FILE" 2>&1
VAL_EXIT=$?

if [ "$VAL_EXIT" -eq 0 ]; then
  gate="pass"
else
  gate="fail"
fi

# Build a YAML-safe list of failing files from the validator output.
# Each "❌ <path>:" line names a failing file. Deduplicate.
# Exclude revise-report.md itself (the gate-value check is a consequence
# of other failures, not a defect in the report file itself).
failed_files=$(grep -E "^❌ " "$VAL_OUT_FILE" \
  | sed -E 's/^❌ ([^:]+):.*/\1/' \
  | grep -v "revise-report\.md$" \
  | grep -v "missing required companion$" \
  | sort -u || true)
failed_yaml="[]"
if [ -n "$failed_files" ]; then
  failed_yaml="["
  first=1
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    base=$(basename "$f")
    if [ $first -eq 1 ]; then
      failed_yaml="${failed_yaml}\"${base}\""
      first=0
    else
      failed_yaml="${failed_yaml}, \"${base}\""
    fi
  done <<< "$failed_files"
  failed_yaml="${failed_yaml}]"
fi

# Write the report.
{
  echo "---"
  echo "revised_at: $NOW"
  echo "engine: $engine"
  echo "plan_files: $plan_count"
  if [ "$engine" = "drill-down-engine" ]; then
    echo "checks_run: [C1, C2, C4, C5, C6, C7, C8]"
  else
    echo "checks_run: [C3, C4, C5, C6, C7, C8]"
  fi
  if [ "$gate" = "pass" ]; then
    echo "checks_passed: [all]"
    echo "checks_failed: []"
  else
    echo "checks_passed: [see regenerations_performed]"
    echo "checks_failed: [validator reported issues in failing_files]"
  fi
  echo "regenerations_performed: []"
  echo "failing_files: $failed_yaml"
  echo "executor_gate: $gate"
  echo "---"
  echo ""
  echo "# Revise Report"
  echo ""
  echo "_Generated by \`scripts/revise.sh\` on $NOW._"
  echo ""
  if [ "$gate" = "pass" ]; then
    echo "All validator checks passed. The plan is cleared for execution."
    echo ""
    echo "Next step: invoke \`prompts/orchestrators/executor.md\` —"
    echo "its preflight will re-run this same validator and then"
    echo "start the execution loop."
  else
    echo "## Failing files"
    echo ""
    echo "Regenerate each of the files below from the originating engine's"
    echo "Step 3. Use the validator output in \`## Validator output\` below"
    echo "to see the exact defect per file."
    echo ""
    while IFS= read -r f; do
      [ -z "$f" ] && continue
      echo "- \`$(basename "$f")\`"
    done <<< "$failed_files"
    echo ""
    echo "After regenerating, re-run: \`bash scripts/revise.sh $TARGET_DIR\`"
    echo ""
  fi
  echo "## Validator output"
  echo ""
  echo '```'
  cat "$VAL_OUT_FILE"
  echo '```'
} > "$REPORT"

rm -f "$VAL_OUT_FILE"

if [ "$gate" = "pass" ]; then
  echo "✅ revise gate: pass — wrote $REPORT"
  exit 0
else
  echo "❌ revise gate: fail — wrote $REPORT with failing_files list"
  echo "   Regenerate the offending files, then re-run this script."
  exit 1
fi
